// Auto-generated by scripts/download-hero-covers.mjs — local novel covers for the landing hero.
export interface HeroCover { slug: string; title: string; genre: string; cover: string; }
export const HERO_COVERS: HeroCover[] = [
  {
    "slug": "im-really-not-the-demon-gods-lackey",
    "title": "I'm Really Not The Demon God's Lackey",
    "genre": "supernatural",
    "cover": "/covers/im-really-not-the-demon-gods-lackey.jpg"
  },
  {
    "slug": "who-let-him-cultivate",
    "title": "Who Let Him Cultivate?!",
    "genre": "eastern",
    "cover": "/covers/who-let-him-cultivate.jpg"
  },
  {
    "slug": "the-second-coming-of-gluttony",
    "title": "The Second Coming of Gluttony",
    "genre": "action",
    "cover": "/covers/the-second-coming-of-gluttony.jpg"
  },
  {
    "slug": "surviving-the-game-as-a-barbarian",
    "title": "Surviving the Game as a Barbarian",
    "genre": "comedy",
    "cover": "/covers/surviving-the-game-as-a-barbarian.jpg"
  },
  {
    "slug": "lord-of-the-mysteries",
    "title": "Lord of the Mysteries",
    "genre": "xuanhuan",
    "cover": "/covers/lord-of-the-mysteries.jpg"
  },
  {
    "slug": "im-an-infinite-regressor-but-ive-got-stories-to-te",
    "title": "I’m an Infinite Regressor, But I’ve Got Stories to Tell",
    "genre": "fantasy",
    "cover": "/covers/im-an-infinite-regressor-but-ive-got-stories-to-te.jpg"
  },
  {
    "slug": "i-shall-seal-the-heavens",
    "title": "I Shall Seal the Heavens",
    "genre": "xianxia",
    "cover": "/covers/i-shall-seal-the-heavens.jpg"
  },
  {
    "slug": "struggling-to-survive-with-regression-power-in-the",
    "title": "Struggling to Survive with Regression Power in the Primordial Saint Sect",
    "genre": "xianxia",
    "cover": "/covers/struggling-to-survive-with-regression-power-in-the.jpg"
  },
  {
    "slug": "the-perfect-run",
    "title": "The Perfect Run",
    "genre": "comedy",
    "cover": "/covers/the-perfect-run.jpg"
  },
  {
    "slug": "steadily-becoming-a-saint-the-immortal-officials-h",
    "title": "Steadily becoming a saint, the immortal officials hired me to tend the horses",
    "genre": "adventure",
    "cover": "/covers/steadily-becoming-a-saint-the-immortal-officials-h.jpg"
  },
  {
    "slug": "kidnapped-dragons-kr-web-novel",
    "title": "Kidnapped Dragons (KR Web Novel)",
    "genre": "action",
    "cover": "/covers/kidnapped-dragons-kr-web-novel.jpg"
  },
  {
    "slug": "jackal-among-snakes",
    "title": "JACKAL AMONG SNAKES",
    "genre": "action",
    "cover": "/covers/jackal-among-snakes.jpg"
  },
  {
    "slug": "under-the-oak-tree",
    "title": "Under the Oak Tree",
    "genre": "romance",
    "cover": "/covers/under-the-oak-tree.jpg"
  },
  {
    "slug": "i-became-the-pope-now-what",
    "title": "I Became The Pope, Now What?",
    "genre": "fantasy",
    "cover": "/covers/i-became-the-pope-now-what.jpg"
  },
  {
    "slug": "birth-of-the-demonic-sword",
    "title": "Birth of the Demonic Sword",
    "genre": "fantasy",
    "cover": "/covers/birth-of-the-demonic-sword.jpg"
  },
  {
    "slug": "dao-of-the-bizarre-immortal",
    "title": "Dao of the Bizarre Immortal",
    "genre": "action",
    "cover": "/covers/dao-of-the-bizarre-immortal.jpg"
  }
];
